[project]
name = "docker_notion"
version = "0.1.0"
description = "docker_notion using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai-tools[mcp]>=1.4.1",
    "crewai[tools]==1.4.1",
    "litellm>=1.80.0",
    "mcp>=1.21.2",
]

[project.scripts]
docker_notion = "docker_notion.main:run"
run_crew = "docker_notion.main:run"
train = "docker_notion.main:train"
replay = "docker_notion.main:replay"
test = "docker_notion.main:test"
run_with_trigger = "docker_notion.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
